add readme
freifunk-gluon/uradvd pull request #1
Opened 2023-03-11 12:15 UTC by mwarning

2023-03-11 12:16 UTC, mwarning commented
A small explanation what on and off link prefix means is still missing.

2023-03-13 20:02 UTC, jplitza requested changes
Good idea, thanks!

Two remarks:
* Please always use addresses and prefixes from 2001:db8::/32 ("db8", as in "debate") for documentation purposes
* The only difference between `-p` and `-a` is the L-flag! The A-flag is always set:
https://github.com/freifunk-gluon/uradvd/blob/9b0da60e27c67305d251b10163e388191d566d7a/uradvd.c#L500-L503
The L-flag means that the receiver is supposed to install a "connected route" for the prefix, while its absence tells the receiver to install a route via the announcing router for the prefix (if it doesn't already have a connected route for it). IMO it doesn't make much sense to set the A-flag without the L-flag, but oh well.

2023-03-13 21:30 UTC, mwarning commented
Updated. Not sure if the explanation is slightly overkill. :D

2025-01-02 04:09 UTC, Neustradamus commented
For information, there is a new radvd version.

2025-01-02 04:36 UTC, mwarning commented
@Neustradamus hm, I do not see any changes in this repository..

2025-01-02 05:50 UTC, Neustradamus commented
@mwarning: It is for this I have done this comment, to inform all ^^

2025-01-02 21:38 UTC, mwarning reviewed
done

2025-05-01 16:16 UTC, merged

2025-05-01 17:23 UTC, mwarning commented
@rotanid thank you

2025-05-01 20:35 UTC, Neustradamus commented
@mwarning: Thanks!

But I discover that my previous comment has noted like "spam", why?

2025-05-01 20:45 UTC, mwarning commented
@Neustradamus I have no idea

2025-05-01 20:47 UTC, Neustradamus commented
@mwarning: You can click on it to change it...